---
- hosts: myhosts
  connection: local
  name: Add User
  gather_facts: False

  # User to add, modify or delete is defined in file group_vars/all

  tasks:

  # When adding a user, you must enable it afterwards
  - name: Add user
    redfish_command:
      category: Accounts
      command: AddUser
      baseuri: "{{ baseuri }}"
      username: "{{ username }}"
      password: "{{ password }}"
      id: "{{ id }}"
      new_username: "{{ new_username }}"
      new_password: "{{ new_password }}"
      roleid: "{{ roleid }}"
