---
- hosts: myhosts
  connection: local
  name: Update user role
  gather_facts: False

  # User to add, modify or delete is defined in file group_vars/all

  tasks:

  - name: Update user role
    redfish_command:
      category: Accounts
      command: Updateroleid
      baseuri: "{{ baseuri }}"
      username: "{{ username }}"
      password: "{{ password }}"
      id: "{{ id }}"
      roleid: "{{ roleid }}"
