---
- hosts: myhosts
  connection: local
  name: Get Manager attributes
  gather_facts: False

  vars:
    datatype: ManagerAttributes

  tasks:

  - name: Set output file
    include_tasks: create_output_file.yml

  - name: Get Manager attributes
    redfish_facts:
      category: Manager
      command: GetManagerAttributes
      baseuri: "{{ baseuri }}"
      username: "{{ username }}"
      password: "{{ password }}"
    register: result

  - name: Copy results to output file
    copy:
      content: "{{ result | to_nice_json }}"
      dest: "{{ template }}.json"
